/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "primary-container": "#58a6ff",
              "on-primary-container": "#003a6b",
              "surface-tint": "#a2c9ff",
              "surface": "#101319",
              "on-primary-fixed-variant": "#004882",
              "on-surface-variant": "#c0c7d4",
              "surface-container-high": "#272a31",
              "surface-container-lowest": "#0b0e14",
              "tertiary-container": "#9ca4ac",
              "primary-fixed": "#d3e4ff",
              "outline-variant": "#414752",
              "surface-bright": "#363940",
              "secondary": "#c1c7d0",
              "on-primary-fixed": "#001c38",
              "error": "#ffb4ab",
              "surface-dim": "#101319",
              "surface-container": "#1d2026",
              "inverse-surface": "#e1e2eb",
              "tertiary-fixed": "#dbe3ec",
              "secondary-fixed": "#dde3ec",
              "on-tertiary": "#293138",
              "surface-variant": "#32353c",
              "on-error": "#690005",
              "on-tertiary-container": "#323a41",
              "on-surface": "#e1e2eb",
              "outline": "#8b919d",
              "error-container": "#93000a",
              "inverse-on-surface": "#2e3037",
              "primary-fixed-dim": "#a2c9ff",
              "secondary-container": "#41474f",
              "secondary-fixed-dim": "#c1c7d0",
              "surface-container-highest": "#32353c",
              "on-error-container": "#ffdad6",
              "on-tertiary-fixed": "#151d22",
              "background": "#101319",
              "tertiary": "#bfc7cf",
              "on-secondary": "#2b3138",
              "surface-container-low": "#191c22",
              "on-secondary-fixed": "#161c23",
              "on-tertiary-fixed-variant": "#40484e",
              "inverse-primary": "#0060aa",
              "on-secondary-container": "#b0b5be",
              "on-secondary-fixed-variant": "#41474f",
              "tertiary-fixed-dim": "#bfc7cf",
              "primary": "#a2c9ff",
              "on-background": "#e1e2eb",
              "on-primary": "#00315c"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Space Grotesk"],
              "body": ["Inter"],
              "label": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
}
