/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "secondary-fixed-dim": "#c3c6cf",
              "inverse-on-surface": "#eaf2fa",
              "surface-bright": "#f6faff",
              "surface-container-low": "#edf4fd",
              "on-secondary": "#ffffff",
              "outline-variant": "#c0c7d4",
              "error-container": "#ffdad6",
              "surface": "#f6faff",
              "on-background": "#151d22",
              "on-tertiary-fixed-variant": "#3f4850",
              "on-primary-fixed": "#001c38",
              "tertiary-fixed-dim": "#bec7d2",
              "on-primary-fixed-variant": "#004882",
              "surface-container-high": "#e1e9f1",
              "primary-fixed": "#d3e4ff",
              "on-error-container": "#93000a",
              "outline": "#717783",
              "surface-container": "#e7eff7",
              "on-primary-container": "#003a6b",
              "on-secondary-fixed-variant": "#43474e",
              "inverse-primary": "#a2c9ff",
              "secondary-fixed": "#dfe2eb",
              "on-surface-variant": "#414752",
              "surface-dim": "#d3dbe3",
              "on-tertiary": "#ffffff",
              "primary": "#0060aa",
              "surface-variant": "#dbe3ec",
              "surface-container-highest": "#dbe3ec",
              "tertiary": "#565f69",
              "on-secondary-container": "#61646c",
              "on-surface": "#151d22",
              "on-tertiary-container": "#313a43",
              "inverse-surface": "#293138",
              "secondary-container": "#dfe2eb",
              "on-tertiary-fixed": "#141c24",
              "on-error": "#ffffff",
              "tertiary-container": "#9ba4ae",
              "primary-container": "#58a6ff",
              "surface-tint": "#0060aa",
              "tertiary-fixed": "#dae3ee",
              "primary-fixed-dim": "#a2c9ff",
              "on-secondary-fixed": "#181c22",
              "on-primary": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "error": "#ba1a1a",
              "background": "#f6faff",
              "secondary": "#5b5e66"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Space Grotesk"],
              "mono": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
}
